# Generated by Django 3.2.13 on 2023-01-10 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField()),
                ('terms_of_service_text', models.TextField()),
                ('curf_id', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfServiceAllSites',
            fields=[
                ('curf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='termsofservice.termsofservice', to_field='curf_id')),
            ],
            options={
                'verbose_name': 'TermsOfServiceAllSite',
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceSites',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
                ('curf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termsofservice.termsofservice', to_field='curf_id')),
            ],
            options={
                'verbose_name': 'TOS Site',
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termsofservice.termsofservice', to_field='curf_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
