# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_schema__add_event_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEventBadgesConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, help_text='The course block identifier.', max_length=255)),
                ('event_type', models.CharField(choices=[(b'chapter_complete', b'Chapter Complete')], db_index=True, default=b'chapter_complete', max_length=32)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.BadgeClass')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='blockeventbadgesconfiguration',
            unique_together=set([('course_id', 'usage_key', 'event_type')]),
        ),
    ]
