# Generated by Django 3.2.12 on 2022-02-10 20:43

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgeclass_badgr_server_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEventBadgesConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, help_text='The course block identifier.', max_length=255)),
                ('event_type', models.CharField(choices=[('chapter_complete', 'Chapter Complete')], db_index=True, default='chapter_complete', max_length=32)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.badgeclass')),
            ],
            options={
                'unique_together': {('course_id', 'usage_key', 'event_type')},
            },
        ),
    ]
