# Generated by Django 3.2.10 on 2022-04-12 13:15

from django.db import migrations, models
import django.db.models.deletion

from opaque_keys.edx.django.models import CourseKeyField


# This should only be used for migrations that have be verified to have a net-neutral sql
# change generated by Django
class NoSqlAlterField(migrations.AlterField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        return

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        return


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_auto_20210702_1602'),
        ('badges', '0005_blockeventbadgesconfiguration'),
    ]

    operations = [
        # Used reference edx-platform/common/djangoapps/course_modes/migrations/0008_course_key_field_to_foreign_key.py to handle this SQL change.
        # We don't want to alter the `course_id` field in the database since there
        # may be existing records in this field.

        # migrations.RemoveField(
        #     model_name='blockeventbadgesconfiguration',
        #     name='course_id',
        # ),
        # migrations.AddField(
        #     model_name='blockeventbadgesconfiguration',
        #     name='course',
        #     field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='block_event_badges_configuration', to='course_overviews.courseoverview'),
        #     preserve_default=False,
        # ),
        # Pin the name of the column in the database so that we can rename the field
        # in Django without generating any sql changes
        migrations.AlterField(
            model_name='blockeventbadgesconfiguration',
            name='course_id',
            field=CourseKeyField(max_length=255, db_index=True, verbose_name="Course", db_column='course_id'),
        ),
        # Change the field name in Django to match our target field name
        migrations.RenameField(
            model_name='blockeventbadgesconfiguration',
            old_name='course_id',
            new_name='course',
        ),
        # Change the type of the field in Django to be a foreign key
        # N.B. we don't need the db_column declaration because the default
        # for Django is to use ${field_name}_id (which is what we pinned the column
        # name to above).
        # We deliberately leave db_constraint set to False because the column
        # isn't currently constrained
        NoSqlAlterField(
            model_name='blockeventbadgesconfiguration',
            name='course',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='block_event_badges_configuration', to='course_overviews.courseoverview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseeventbadgesconfiguration',
            name='course_groups',
            field=models.TextField(blank=True, default='', help_text="Each line is a comma-separated list. The first item in each line is the slug of abadge class you have created that has an issuing component of 'openedx__course'. Theremaining items in each line are the course keys the learner needs to complete to beawarded the badge. For example: slug_for_compsci_courses_group_badge,course-v1:CompSci+Course+First,course-v1:CompsSci+Course+Second"),
        ),
        migrations.AlterField(
            model_name='courseeventbadgesconfiguration',
            name='courses_completed',
            field=models.TextField(blank=True, default='', help_text="On each line, put the number of completed courses to award a badge for, a comma, andthe slug of a badge class you have created that has the issuing component 'openedx__course'. For example: 3,enrolled_3_courses"),
        ),
        migrations.AlterField(
            model_name='courseeventbadgesconfiguration',
            name='courses_enrolled',
            field=models.TextField(blank=True, default='', help_text="On each line, put the number of enrolled courses to award a badge for, a comma, andthe slug of a badge class you have created that has the issuing component'openedx__course'. For example: 3,enrolled_3_courses"),
        ),
    ]
