# Generated by Django 2.2.15 on 2021-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_remove_course_id_mode_unique_together_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeventbadgesconfiguration',
            name='event_type',
            field=models.CharField(choices=[('chapter_complete', 'Chapter Complete')], db_index=True, default='chapter_complete', max_length=32),
        ),
    ]
