# Generated by Django 3.2.10 on 2022-04-12 19:35

from django.db import migrations


class NoSqlAlterUniqueTogether(migrations.AlterUniqueTogether):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        return

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        return


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_auto_20210702_1602'),
        ('badges', '0006_auto_20220412_1315'),
    ]

    operations = [
        NoSqlAlterUniqueTogether(
            name='blockeventbadgesconfiguration',
            unique_together={('course_id', 'usage_key', 'event_type')},
        ),
    ]
