# Generated by Django 3.2.13 on 2023-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_auto_20210702_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='revision_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='revision_number',
            field=models.TextField(null=True),
        ),
    ]
