# Generated by Django 3.2.13 on 2024-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_auto_20230525_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_institution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_institution',
            field=models.TextField(null=True),
        ),
    ]
