# Generated by Django 3.2.16 on 2024-01-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_auto_20230525_1917'),
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
    ]
