# Generated by Django 3.2.16 on 2024-12-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_auto_20240909_1523'),
        ('course_overviews', '0027_merge_20240123_1603'),
    ]

    operations = [
    ]
