# Generated by Django 3.2.16 on 2024-07-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_merge_20240123_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_institution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_institution',
            field=models.TextField(null=True),
        ),
    ]
