# Generated by Django 3.2.13 on 2022-10-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='promote_to_banner',
            field=models.BooleanField(default=False),
        ),
    ]
