# Generated by Django 2.2.15 on 2021-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0022_emailproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='key',
            field=models.TextField(blank=True, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='secret',
            field=models.TextField(blank=True, help_text='For increased security, you can avoid storing this in your database by leaving  this field blank and setting SOCIAL_AUTH_OAUTH_SECRETS = {"(backend name)": "secret", ...} in your instance\'s Django settings (or lms.auth.json)', verbose_name='Client Secret'),
        ),
    ]
