# Generated by Django 3.2.10 on 2022-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0006_emailproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='key',
            field=models.TextField(blank=True, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='secret',
            field=models.TextField(blank=True, help_text='For increased security, you can avoid storing this in your database by leaving  this field blank and setting SOCIAL_AUTH_OAUTH_SECRETS = {"(backend name)": "secret", ...} in your instance\'s Django settings (or lms.auth.json)', verbose_name='Client Secret'),
        ),
    ]
