# Generated by Django 3.2.16 on 2024-01-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0007_auto_20220121_1956'),
        ('third_party_auth', '0008_auto_20220324_1422'),
    ]

    operations = [
    ]
