# Generated by Django 3.2.16 on 2024-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0009_merge_0007_auto_20220121_1956_0008_auto_20220324_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='was_valid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamped field that indicates a user has successfully logged in using this configuration at least once.', null=True),
        ),
        migrations.AlterField(
            model_name='emailproviderconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this provider (shown to users)', max_length=50),
        ),
    ]
