# Generated by Django 2.2.15 on 2021-10-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.IntegerField()),
                ('bc_email', models.EmailField(max_length=255, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.IntegerField()),
                ('bc_email', models.EmailField(max_length=255, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_hash', models.CharField(max_length=16, unique=True)),
                ('access_token', models.CharField(max_length=128)),
                ('scope', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_app.Customer')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_app.Store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCustomerPlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_store_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_app.StoreCustomer')),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('bc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_app.AdminUser')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_app.Store')),
            ],
        ),
    ]
