# Generated by Django 2.2.15 on 2021-10-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeadminuser',
            old_name='bc_user',
            new_name='bc_admin_user_id',
        ),
        migrations.RenameField(
            model_name='storeadminuser',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
