# Generated by Django 2.2.15 on 2021-10-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0002_auto_20211015_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeadminuser',
            old_name='bc_admin_user_id',
            new_name='bc_admin_user',
        ),
        migrations.RenameField(
            model_name='storeadminuser',
            old_name='store_id',
            new_name='store',
        ),
    ]
