# Generated by Django 2.2.15 on 2021-10-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0003_auto_20211015_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storecustomer',
            old_name='bc_customer_id',
            new_name='bc_customer',
        ),
        migrations.RenameField(
            model_name='storecustomer',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storecustomerplatformuser',
            old_name='bc_store_customer_id',
            new_name='bc_store_customer',
        ),
    ]
