# Generated by Django 2.2.15 on 2021-10-19 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0004_auto_20211015_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bc_group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeadminuser',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bigcommerce_app.Store'),
        ),
        migrations.AlterField(
            model_name='storecustomer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bigcommerce_app.Store'),
        ),
    ]
