# Generated by Django 2.2.15 on 2021-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0005_auto_20211019_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bc_first_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bc_last_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
