# Generated by Django 2.2.15 on 2021-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0006_auto_20211021_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bc_first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bc_group_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bc_last_name',
            field=models.TextField(blank=True),
        ),
    ]
