# Generated by Django 2.2.15 on 2021-10-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0007_auto_20211021_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bc_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
