# Generated by Django 3.2.13 on 2022-08-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0008_auto_20211021_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bc_country_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bc_postal_code',
            field=models.TextField(blank=True),
        ),
    ]
