# Generated by Django 3.2.16 on 2024-01-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_app', '0009_auto_20220823_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bc_country_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bc_postal_code',
        ),
    ]
