# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-08-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_coursenrollment_course_on_delete_do_nothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'm', b'Male'), (b'f', b'Female'), (b'nbtg', b'Non-binary / third gender'), (b'prefer-not-to-say', b'Prefer not to say'), (b'o', b'Other')], db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[(b'p', b'Doctorate'), (b'm', b"Master's or professional degree"), (b'b', b"Bachelor's degree"), (b'a', b'Associate degree'), (b'hs', b'Secondary/high school'), (b'jhs', b'Junior secondary/junior high/middle school'), (b'el', b'Elementary/primary school'), (b'none', b'No formal education'), (b'other', b'Other education')], db_index=True, max_length=25, null=True),
        ),
    ]
