# Generated by Django 3.2.13 on 2022-08-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_remove_userprofile_allow_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('nbtg', 'Non-binary / third gender'), ('prefer-not-to-say', 'Prefer not to say'), ('o', 'Other')], db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('some-hs', 'Some high school'), ('hs', 'High School or GED'), ('some-college', 'Some college'), ('a', '2-year degree'), ('b', '4-year degree'), ('m', "Master's"), ('p', 'Doctorate'), ('jd-md', 'Professional degree (J.D., M.D.)'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollmentcelebration',
            name='celebrate_weekly_goal',
            field=models.BooleanField(default=False),
        ),
    ]
