# Generated by Django 3.2.16 on 2024-02-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
        ('student', '0046_alter_userprofile_level_of_education'),
    ]

    operations = [
    ]
