# Generated by Django 3.2.16 on 2025-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_merge_20240214_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('t', 'Transgender'), ('nbnc', 'Non-binary / Non-Conforming'), ('o', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=25, null=True),
        ),
    ]
