# Generated by Django 3.2.16 on 2025-03-24 19:36

from django.db import migrations

def alter_gender_data(apps, schema_editor):
    # gets the user profile model
    userprofile = apps.get_model('student', 'userprofile')

    # update data
    for user in userprofile.objects.filter(gender='nbtg'):
        user.gender = 'nbnc'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0048_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RunPython(alter_gender_data),
    ]
